// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgyCZy8-DmR5rvsrD8U_wmk_m7QiEyfJg',
    appId: '1:16435055010:web:6bae2aeb58dc5f49fe0afb',
    messagingSenderId: '16435055010',
    projectId: 'injustice-app-davibriel',
    authDomain: 'injustice-app-davibriel.firebaseapp.com',
    storageBucket: 'injustice-app-davibriel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAF1rYQLCh8hMExj8biTULcz_UrL6T45Y',
    appId: '1:16435055010:android:c7ac3a9247eca1aefe0afb',
    messagingSenderId: '16435055010',
    projectId: 'injustice-app-davibriel',
    storageBucket: 'injustice-app-davibriel.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCysRgNqUqMtNj5qkho9rdD6bvUES6w2fY',
    appId: '1:16435055010:ios:b677d4b98356a692fe0afb',
    messagingSenderId: '16435055010',
    projectId: 'injustice-app-davibriel',
    storageBucket: 'injustice-app-davibriel.firebasestorage.app',
    iosBundleId: 'com.example.injusticeApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCysRgNqUqMtNj5qkho9rdD6bvUES6w2fY',
    appId: '1:16435055010:ios:b677d4b98356a692fe0afb',
    messagingSenderId: '16435055010',
    projectId: 'injustice-app-davibriel',
    storageBucket: 'injustice-app-davibriel.firebasestorage.app',
    iosBundleId: 'com.example.injusticeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgyCZy8-DmR5rvsrD8U_wmk_m7QiEyfJg',
    appId: '1:16435055010:web:c014a7b684c940e6fe0afb',
    messagingSenderId: '16435055010',
    projectId: 'injustice-app-davibriel',
    authDomain: 'injustice-app-davibriel.firebaseapp.com',
    storageBucket: 'injustice-app-davibriel.firebasestorage.app',
  );
}
