// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9t3gvTMUBrthoSEN-0yFLets7N1ePVfk',
    appId: '1:962884197905:web:c51ca10e57343ac19ddbb0',
    messagingSenderId: '962884197905',
    projectId: 'injusticeapp-48ed3',
    authDomain: 'injusticeapp-48ed3.firebaseapp.com',
    storageBucket: 'injusticeapp-48ed3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhFjK8hbyGUYvsFKy5Jz8xSBDYMV6h0Oc',
    appId: '1:962884197905:android:6be0217912f9a1eb9ddbb0',
    messagingSenderId: '962884197905',
    projectId: 'injusticeapp-48ed3',
    storageBucket: 'injusticeapp-48ed3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdrksKUYfcNRf61axRbC_pdImLyPsQ2SI',
    appId: '1:962884197905:ios:6458efd755a895a89ddbb0',
    messagingSenderId: '962884197905',
    projectId: 'injusticeapp-48ed3',
    storageBucket: 'injusticeapp-48ed3.firebasestorage.app',
    iosBundleId: 'com.example.injusticeApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdrksKUYfcNRf61axRbC_pdImLyPsQ2SI',
    appId: '1:962884197905:ios:6458efd755a895a89ddbb0',
    messagingSenderId: '962884197905',
    projectId: 'injusticeapp-48ed3',
    storageBucket: 'injusticeapp-48ed3.firebasestorage.app',
    iosBundleId: 'com.example.injusticeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9t3gvTMUBrthoSEN-0yFLets7N1ePVfk',
    appId: '1:962884197905:web:2e3c9c5361aa878b9ddbb0',
    messagingSenderId: '962884197905',
    projectId: 'injusticeapp-48ed3',
    authDomain: 'injusticeapp-48ed3.firebaseapp.com',
    storageBucket: 'injusticeapp-48ed3.firebasestorage.app',
  );
}
